<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{30cfc5af-b74e-445a-b332-297f92c143cd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	my_counter : INT := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[my_counter := my_counter + 1;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>